[features]
seeds = false
skip-lint = false

[programs.mainnet]
poi = "HGDCZkwnD3vXkjdMUugEdimLoZB87TyQLHgz1Ro346y7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
